services:
  panel:
    build:
      args:
        user: {YOUR-USER-NAME}
        uid: 5000
      context: ./
      dockerfile: Dockerfile
    image: enigmaimgv2
    container_name: enigmacontv2
    #restart: on-failure #unless-stopped
    working_dir: /home
    volumes:
      - ./data/:/home/data
      - ./output/:/home/output

